import { Oswald } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { ToastContainer } from 'react-toastify'

const oswald = Oswald({
	subsets: ['latin'],
	weight: ['400', '500', '700'],
	variable: '--font-oswald',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en' className={`${oswald.variable} h-full antialiased`}>
			<body className={`${oswald.className} min-h-full flex flex-col`}>
				<ToastContainer></ToastContainer>
				<Navbar></Navbar>
				{children}
				<Footer></Footer>
			</body>
		</html>
	)
}
